# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 21:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_place_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityitinerary',
            name='num_days',
        ),
        migrations.AddField(
            model_name='cityitinerary',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cityitinerary',
            name='end_date',
            field=models.DateField(default=datetime.date(2100, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cityitinerary',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='start_date',
            field=models.DateField(),
        ),
    ]
